export const FrontEnd = 
[{
    "id":1,
    "languageName":"Html",
    "languageImage":"/html.svg",
    "languageProgress":100
},
{
    "id":2,
    "languageName":"Css",
    "languageImage":"/css.svg",
    "languageProgress":50
},{
    "id":3,
    "languageName":"Tailwind Css",
    "languageImage":"/tailwindcss.svg",
    "languageProgress":90
},{
    "id":4,
    "languageName":"Next.js",
    "languageImage":"/nextjs.svg",
    "languageProgress":60
},{
    "id":5,
    "languageName":"Vite",
    "languageImage":"/vite.svg",
    "languageProgress":70
},{
    "id":6,
    "languageName":"React",
    "languageImage":"/react.svg",
    "languageProgress":70
},{
    "id":7,
    "languageName":"JS",
    "languageImage":"/javascript.svg",
    "languageProgress":70
},{
    "id":8,
    "languageName":"Redux",
    "languageImage":"/redux.svg",
    "languageProgress":40
}]
export const BackEnd = 
[{
    "id":1,
    "languageName":"Laravel",
    "languageImage":"/laravel.svg",
    "languageProgress":50
},
{
    "id":2,
    "languageName":"PHP",
    "languageImage":"/php.svg",
    "languageProgress":50
},{
    "id":3,
    "languageName":"MongoDB",
    "languageImage":"/mongodb.svg",
    "languageProgress":30
},{
    "id":4,
    "languageName":"sql",
    "languageImage":"/sql.svg",
    "languageProgress":50
}]
export const Designe = 
[{
    "id":1,
    "languageName":"Figma",
    "languageImage":"/figma.svg",
    "languageProgress":50
},
{
    "id":2,
    "languageName":"Canva",
    "languageImage":"/canva.svg",
    "languageProgress":50
}]